name: Deploy Application

on: workflow_dispatch

jobs:
  deploy:
    runs-on: [self-hosted]
    defaults:
      run:
        working-directory: /home/ubuntu/app
    steps:
      - name: Clean directory
        run: rm -rf /home/ubuntu/app && mkdir /home/ubuntu/app
      - name: Clone Repository
        run: gh repo clone lipex360x/rest-api-boilerplate .
      - name: Install packages
        run: yarn
      - name: Build App
        run: yarn build
      - name: PM2 Startup
        run: |
          pm2 delete all || : && pm2 start .build/server.js -i 1 --name api
      - name: PM2 save
        run: pm2 save --force
